### ISSUE TITLE
How to use Okendo with Gatsby?

### ISSUE THREAD

**Issue by hotcakedev628** [getnacelle/nacelle-react#39]
I am using Nacelle with Gatsby, but I have no idea how to use Okendo with Gatsby?
https://docs.getnacelle.com/nuxt/okendo.html#okendo-setup

Gatsby doesn't have Okendo module, right?
Then is there no way to use Okendo with Gatsby?
Should I just use only Klavyio and Yotpo?

**Comment by NWRichmond** [comment]
Hi @hotcakedev628!

> Should I just use only Klavyio and Yotpo?

We can't offer advice about which third-party services to use. But if you do choose to use Klaviyo or Yotpo, please feel free to use the [`@nacelle/react-klaviyo`](https://www.npmjs.com/package/@nacelle/react-klaviyo) and / or [`@nacelle/react-yotpo`](https://www.npmjs.com/package/@nacelle/react-yotpo) packages from [this monorepo](https://github.com/getnacelle/nacelle-react/tree/main/packages).

> I am using Nacelle with Gatsby, but I have no idea how to use Okendo with Gatsby?

That's a bit outside the scope of this repo, but I would think that leveraging Okendo in React components wouldn't involve any Gatsby-specific work.

I reached out to the Okendo team to ask if there are any plans to create a React equivalent of their [`@okendo/okendo-widgets-vue`](https://www.npmjs.com/package/@okendo/okendo-widgets-vue) package. They said that they don't have any immediate plans, but added that some developers have been successful with creating their own React components that work in tandem with Okendo's APIs.

Since their APIs don't have public docs, I'd recommend reaching out to the Okendo team directly to get a sense of what's required. You can get in touch with them via the chat widget on [support.okendo.io](https://support.okendo.io):

https://user-images.githubusercontent.com/5732000/112897965-428a4800-90ae-11eb-99b7-5f7c2fe6752e.mov
